export const generateWordList = () => {
  return [
    { display: "りんご", furigana: "りんご", kanji: "林檎", typing: "ringo" },
    { display: "バナナ", furigana: "ばなな", kanji: "バナナ", typing: "banana" },
    { display: "さくらんぼ", furigana: "さくらんぼ", kanji: "桜", typing: "sakurannbo" },
    { display: "なつめやし", furigana: "なつめやし", kanji: "棗", typing: "natume" },
    { display: "にわとこ", furigana: "にわとこ", kanji: "接骨木", typing: "niwatoko" },
    { display: "いちじく", furigana: "いちじく", kanji: "無花果", typing: "ichijiku" },
    { display: "ぶどう", furigana: "ぶどう", kanji: "葡萄", typing: "budou" },
    { display: "メロン", furigana: "めろん", kanji: "メロン", typing: "meron" },
    { display: "キウイ", furigana: "きうい", kanji: "キウイ", typing: "kiui" },
    { display: "レモン", furigana: "れもん", kanji: "檸檬", typing: "remon" },
    { display: "マンゴー", furigana: "まんごー", kanji: "マンゴー", typing: "mango-" },
    { display: "ネクタリン", furigana: "ねくたりん", kanji: "ネクタリン", typing: "nekutarin" },
    { display: "オレンジ", furigana: "おれんじ", kanji: "オレンジ", typing: "orenji" },
    { display: "パパイヤ", furigana: "ぱぱいや", kanji: "パパイヤ", typing: "papaiya" },
    { display: "クインス", furigana: "くいんす", kanji: "クインス", typing: "kuinsu" },
    { display: "ラズベリー", furigana: "らずべりー", kanji: "ラズベリー", typing: "razuberii-" },
    { display: "イチゴ", furigana: "いちご", kanji: "苺", typing: "ichigo" },
    { display: "タンジェリン", furigana: "たんじぇりん", kanji: "タンジェリン", typing: "tanjyeriin" },
    { display: "ウグリ", furigana: "うぐり", kanji: "ウグリ", typing: "uguri" },
    { display: "スミレ", furigana: "すみれ", kanji: "菫", typing: "sumire" },
    { display: "スイカ", furigana: "すいか", kanji: "西瓜", typing: "suika" },
    { display: "シクワ", furigana: "しくわ", kanji: "シクワ", typing: "shikuwa" },
    { display: "ヤム", furigana: "やむ", kanji: "ヤム", typing: "yamu" },
    { display: "ズッキーニ", furigana: "ずっきーに", kanji: "ズッキーニ", typing: "zukki-ni" },
    { display: "アボカド", furigana: "あぼかど", kanji: "アボカド", typing: "abokado" },
    { display: "ブラックベリー", furigana: "ぶらっくべりー", kanji: "ブラックベリー", typing: "burakkuberi-" },
    { display: "カンタロープ", furigana: "かんたろーぷ", kanji: "カンタロープ", typing: "kantaro-pu" },
    { display: "ドラゴンフルーツ", furigana: "どらごんふるーつ", kanji: "ドラゴンフルーツ", typing: "doragonfuru-tsu" },
    { display: "ナス", furigana: "なす", kanji: "茄子", typing: "nasu" },
    { display: "グーズベリー", furigana: "ぐーずべりー", kanji: "グーズベリー", typing: "gu-zuberi-" }
  ];
};
